#!/usr/bin/env python3
"""This script defines an asynchronous function
`async_comprehension` that utilizes an asynchronous
generator to create a list of random float numbers."""

import random
import asyncio
from typing import List
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """Asynchronously collects a list of 10 random float
    numbers generated by the `async_generator` coroutine."""
    lst: List[float] = [i async for i in async_generator()]  # Asynchronous list comprehension
    return lst
